name: GitHub Pages

on:
  push:
    branches:
      
main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      
name: Checkout code
      uses: actions/checkout@v2

      
name: Set up Jekyll
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'

      
name: Install dependencies
      run: |
        gem install jekyll
        gem install bundler

      
name: Build and Deploy
      run: |
        bundle exec jekyll build
        git push origin main
